CREATE DATABASE yeticave_834473
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE yeticave_834473;

CREATE TABLE categories (
  category_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR (128) NOT NULL UNIQUE,
  alias VARCHAR (128) NOT NULL UNIQUE
);

CREATE TABLE users (
  user_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR (128) NOT NULL UNIQUE,
  name VARCHAR (50) NOT NULL,
  password VARCHAR (64) NOT NULL,
  date_reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  avatar VARCHAR (64),
  contact_information VARCHAR (255) NOT NULL
);

CREATE TABLE lots (
  lot_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR (128) NOT NULL,
  description VARCHAR (255) NOT NULL,
  image VARCHAR (64) NOT NULL,
  start_price INT UNSIGNED NOT NULL,
  completion_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  step_rate INT UNSIGNED NOT NULL,
  author_id INT UNSIGNED NOT NULL,
  winner_id INT UNSIGNED,
  category_id SMALLINT UNSIGNED NOT NULL,
  FOREIGN KEY (category_id) REFERENCES categories (category_id),
  FOREIGN KEY (author_id) REFERENCES users (user_id),
  FOREIGN KEY (winner_id) REFERENCES users (user_id),
  FULLTEXT INDEX title_description_ft_idx (title,description)
);

CREATE TABLE rates (
  rate_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  rate INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  lot_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (user_id),
  FOREIGN KEY (lot_id) REFERENCES lots (lot_id)
);
